#!/usr/bin/env php
<?php
require __DIR__ . '/boostrap.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new Absszero\PSStore\MigrationCommand);
$application->add(new Absszero\PSStore\Track\AddCommand);
$application->add(new Absszero\PSStore\Track\ListCommand);
$application->add(new Absszero\PSStore\Track\DelCommand);
$application->add(new Absszero\PSStore\Track\GoCommand);

/*$application->add(new Absszero\PSStore\Notifier\Index);
$application->add(new Absszero\PSStore\Notifier\Add);
$application->add(new Absszero\PSStore\Notifier\Remove);*/

$application->run();
